name: Find Free Fire Offsets

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  analyze-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Репозиторийді жүктеп алу
        uses: actions/checkout@v4

      - name: Python ортасын орнату
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Офсеттерді автоматты іздеу
        run: |
          python main.py
