name: Find APK Offsets

on:
  workflow_dispatch:

jobs:
  find-offsets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download APK from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download v1.0.0 --repo ${{ github.repository }} --pattern "*.apk"
          ls -lh

      - name: Run Offset Finder
        run: |
          python main.py "Free Fire.8.apk"
